### ISSUE TITLE
incorrect variable being checked is incorrect for example

### ISSUE THREAD

**Issue by evillgenius75** [PacktPublishing/Cloud-Native-Applications-with-Ballerina#1]
https://github.com/PacktPublishing/Cloud-Native-Applications-with-Ballerina/blob/1f81554f2d44fc058dbbcb9ee008aa48d7b02b0a/Chapter02/error_handling/main.bal#L15

Should be 
`if decodederrorTime is time:Utc {`

**Comment by madushadhanushka** [comment]
This has been fixed. Thank you for reporting.
